### ISSUE TITLE
TypeError: subcon should be a Construct field

### ISSUE THREAD

**Issue by berlund** [rytilahti/python-eq3bt#16] opened 2018-01-18 21:07 UTC
Error when calling the cli tool like this

```
~/eq3 $ eq3cli 
Traceback (most recent call last):
  File "/home/pi/eq3/bin/eq3cli", line 7, in <module>
    from eq3bt.eq3cli import cli
  File "/home/pi/eq3/lib/python3.5/site-packages/eq3bt/__init__.py", line 2, in <module>
    from .eq3btsmart import Thermostat, TemperatureException, Mode
  File "/home/pi/eq3/lib/python3.5/site-packages/eq3bt/eq3btsmart.py", line 17, in <module>
    from .structures import *
  File "/home/pi/eq3/lib/python3.5/site-packages/eq3bt/structures.py", line 79, in <module>
    "cmd" / Const(Int8ub, PROP_INFO_RETURN),
  File "/home/pi/eq3/lib/python3.5/site-packages/construct/core.py", line 1277, in __init__
    super(Const, self).__init__(subcon)
  File "/home/pi/eq3/lib/python3.5/site-packages/construct/core.py", line 287, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field
```

Is this a Python 3.5 related issue?

**Comment by rytilahti** [comment] 2018-01-18 22:15
Duplicate of #13.

**Closed by rytilahti** 2018-01-18 22:15 UTC
